<div>
  <h2>
    About.
  </h2>
  <div>
    This is a blog.
  </div>
</div>
  
  <div id="global-recent-posts">
    <h2>
      Recent Posts
    </h2>
    <ul class="post-list">
      <li>
        <a href="/posts/welcome-to-nikola/index.html" class="listtitle">Welcome to Nikola</a>
      </li>
    </ul>
  </div>

  
        <div id="global-category-list">
          <h2>
            Categories
          </h2>
          <ul class="category-level category-level-1">
            <li><a class="reference" href="/categories/cat_nikola/index.html">nikola</a> (1)
            </li>
          </ul>
        </div>

  

        <div id="global-archive-list">
          <h2>
            Archives
          </h2>
          <ul class="archive-level archive-level-1">
            <li><a class="reference" href="/2012/index.html">2012</a> (1)
            </li>
          </ul>
        </div>


  
        <div id="global-tag-list">
          <h2>
            Tags
          </h2>
          <ul>
            <li><a class="reference" href="/categories/blog/index.html">blog</a> (1)</li>
            <li><a class="reference" href="/categories/demo/index.html">demo</a> (1)</li>
            <li><a class="reference" href="/categories/nikola/index.html">nikola</a> (1)</li>
            <li><a class="reference" href="/categories/python/index.html">python</a> (1)</li>
          </ul>
        </div>

